# Generated by Django 5.0.4 on 2024-05-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_panel', '0005_comment_user_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
